name: HealthCheck Interval

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 6 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2.2
        with:
          url: https://salty-caverns-08525.herokuapp.com
          max-attempts: 3
          retry-delay: 5s